### ISSUE TITLE
Release 4.2.4 is missing files.

### ISSUE THREAD

**Issue by MrEbbinghaus** [JamesIves/github-pages-deploy-action#1039] opened 2022-02-16 14:25 UTC
Hey.

It seems like the latest release 4.2.4 is missing the compiled JS files:

I get the error:
```
File not found: '/home/runner/work/_actions/JamesIves/github-pages-deploy-action/v4/lib/main.js'
```

Contents of the release:
```
.
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── SECURITY.md
├── __tests__
│   ├── env.js
│   ├── execute.test.ts
│   ├── git.test.ts
│   ├── main.test.ts
│   ├── ssh.test.ts
│   ├── util.test.ts
│   ├── worktree.error.test.ts
│   └── worktree.test.ts
├── action.yml
├── integration
│   ├── image.jpg
│   └── index.html
├── jest.config.js
├── package.json
├── src
│   ├── constants.ts
│   ├── execute.ts
│   ├── git.ts
│   ├── lib.ts
│   ├── main.ts
│   ├── ssh.ts
│   ├── util.ts
│   └── worktree.ts
├── tsconfig.json
├── tsconfig.lint.json
└── yarn.lock
```

**Comment by JamesIves** [comment] 2022-02-16 14:59
Should be fixed now, thanks for the report. This was caused by a mis-click in the release UI that cut a version based on the dev branch as opposed to the release branch. 

If you're not already [I strongly suggest moving away from major version tags](https://jamesiv.es/blog/javascript/security/2022/02/13/when-package-dependencies-become-problematic/) in favor of specific version numbers and relying on Dependabot for these updates.

**Closed as completed by JamesIves** 2022-02-16 15:00 UTC
Labels: bug 🐝, priority ‼️, version 4
