### ISSUE TITLE
Support building without deploying

### ISSUE THREAD

**Issue by patcon** [JamesIves/github-pages-deploy-action#106] opened 2020-01-06 20:02 UTC
**Is your feature request related to a problem? Please describe.**

Seems from action that the action can only deploy, and can't build without deploying. This is useful when there are tests to be run before deploy, such as the html-proofer gem that does a bunch of checks for valid html.

**Describe the solution you'd like**

I'd love for a `SKIP_DEPLOY` flag, so that I can create a test workflow that has an additional step of my own for running a custom script on the build website. This would run in pull requests.

**Additional Comments**

Thanks so so much for offering this action, and any consideration you might give this :)

**Comment by JamesIves** [comment] 2020-01-06 20:27
Could you show me a workflow file where this would be applicable? The action by design no longer builds anything in version 3 so you could simply not include it in your workflow for when a pull request is made.

**Comment by patcon** [comment] 2020-01-07 04:55
Thanks for reply!

> no longer builds anything 

Sorry, you're saying it doesn't build anything into build dir via `jekyll build`? If not, then I'll have to investigate, as I'm confused how this works :)

**Comment by JamesIves** [comment] 2020-01-07 12:35
Can you link me your workflow file? I’d like to see what version you’re running.

**Comment by patcon** [comment] 2020-01-07 15:21
to clarify, i'm not running any version yet. was looking at this to migrate from a circleCI config, but not seeing a way to run our tests on a built website directory without deploying on each PR push.

Does that sound reasonable to aspire to do with this action?

**Comment by brockfanning** [comment] 2020-01-07 15:41
@patcon In case it helps to see a usage example, [here](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/.github/workflows/test-pull-requests.yml) is a workflow that does a Jekyll build and tests it, on each pull-request. And [here](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/.github/workflows/deploy-to-staging.yml) is a workflow that does a Jekyll build and then deploys it using this action.

**Comment by JamesIves** [comment] 2020-01-07 18:13
Thanks @brockfanning - I'm going to close this discussion.

**Closed by JamesIves** 2020-01-07 18:13 UTC
Labels: support 📞
