### ISSUE TITLE
When change index.html during build it is overwritten 

### ISSUE THREAD

**Issue by justgook** [JamesIves/github-pages-deploy-action#166] opened 2020-02-01 03:09 UTC
i have folder `gh-pages` - that then is deployed to `gh-pages` branch, during build i rewrite `index.html`
when it is deployed it takes original `index.html` (not yet clear it takes it from `master`, or `gh-pages` branch) - but as result i got deployed not by updated file, but that how it looks originally

**Comment by JamesIves** [comment] 2020-02-01 03:15
Can you provide an example of your workflow or log files?

**Comment by justgook** [comment] 2020-02-07 13:07
https://github.com/justgook/webgl-playground/blob/dee7cc1226904d7f2d3eeea563b88424b42010ca/.github/workflows/build.yml#L94

**Comment by justgook** [comment] 2020-02-07 13:12
main idea is - that im have "index.html" - that is used while development, then - same file is processed via `posthtml` - and some part of that is changed during build..

then comes step of deployment, that do:
`/usr/bin/git checkout --progress --force master`
that clean up changes made in `index.html` file...

**Comment by JamesIves** [comment] 2020-02-11 13:34
Ah I see what's happening here. Because `index.html` is tracked the action is checking out whatever is on the remote instead of it being pulled from the modified version within the action workflow.

I think a good workaround for this would be to modify your build step so it moves the data into a folder that isn't tracked. Perhaps you could add a `cp` command that moves the processed index file to a `build` folder and then use that as your `FOLDER` configuration in the deploy step.

Sorry for the late reply, I've been traveling the last couple of weekends. Let me know if that works for you.

**Comment by justgook** [comment] 2020-02-13 09:26
that kind of works, I did that by using `index_template.html` - that is converted to the `index.thml` - but that is regression from the previous version...

**Comment by JamesIves** [comment] 2020-02-14 02:46
> but that is regression from the previous version...

This is how this has always worked with this action, were you seeing different behavior previously?

**Comment by justgook** [comment] 2020-02-17 08:44
I had no issues with previous versions (as far as I remember) - but need to recheck

**Comment by JamesIves** [comment] 2020-02-17 13:36
Closing for now.

**Comment by kratsg** [comment] 2020-06-08 15:40
I ran into this undocumented feature as well. It's not clear that the action explicitly resets all changes in the git repository (and I don't have `CLEAN` enabled). The way I'm trying to get around this is by making a template file that I copy to a new file that I will deploy with.

**Comment by JamesIves** [comment] 2020-06-08 18:04
It's not really a feature, the action takes advantage of the git process to toggle between branches, if the files are tracked it's going to reset them when it checks out the specified branch.  It's a pretty common practice for most web projects to build into a dist folder or something similar which is why I haven't prioritized this request. 

If you'd like to have a go at implementing this and creating a pull request you could probably wrap this code in a check to see if `action.folder === action.root` and not run it. This should prevent the git process from fetching the latest copy (although you'd lose the ability for the action to create the branch for you), either that or make it preserve the changes when the branch is switched via stashing.

https://github.com/JamesIves/github-pages-deploy-action/blob/dev/CONTRIBUTING.md

**Comment by AZMCode** [comment] 2020-07-31 20:44
I've tried this solution, and have found no success yet. I got a "Exiting early, nothing to commit" error. 

> Perhaps a PRESERVE_CHANGES option that stashes anything and pulls from the stash before/and this.

Please, this. Can we reopen this as a feature request?

**Comment by JamesIves** [comment] 2020-08-02 13:20
From what I understand this issue is being caused by tracked files being directly modified in the workflow as opposed to making a copy of them. You should be able to resolve your issue using the following steps:

* Add a build step using node or something similar to modify the file, and push the "built" page into a `dist` folder. Run this after `checkout` but before the deploy step.
* Add `dist` to your `.gitignore`
* Tell the deploy action to deploy the `dist` folder as opposed to the project root.

I'm happy to re-open if you feel this would be a useful feature though.

**Comment by oldgalileo** [comment] 2020-09-24 20:40
Would like to echo that a "PRESERVE_WORKDIR" flag would be welcomed with open arms. Spent some time tearing my hair out wondering where my changes from `sed` were going until I came across this issue which confirmed what I had started to suspect.

**Comment by JamesIves** [comment] 2020-09-25 14:15
I've got a test version of this available. Please point your workflows to `releases/v3-cname` and toggle the following option:

```
PRESERVE: true`
```

The action will run `git stash` after the repository has been initialized in the workplace before the first fetch, and then `git stash apply` before the action adds the worktree/commits. Please give this a shot and let me know if this works for you. 

Additionally if there's no stash available for it to apply right now it will error the flow and exit early, when this is tested/ready for release I'll allow the action to tolerate this error.

Keep me posted!

**Comment by oldgalileo** [comment] 2020-09-25 17:42
Wow that was fast @JamesIves. Just deployed v3-cname to a few staging sites and it looks like everything is working as expected with changes properly persisting.

**Comment by JamesIves** [comment] 2020-09-26 14:54
That's great to hear. I'm wondering what should be done incase the stash command either encounters a conflict or fails as there's nothing in the stash. If it does it's going to interrupt the workflow and cause a failure. Is there some sort of command line trick for stash that always prefers the content over the current head? This may also be a moot point as technically it's always going to be ahead based on how the action toggles between the branches to prepare the workflow.

**Comment by JamesIves** [comment] 2020-09-27 18:44
I've released this as part of `3.6.2` as an experimental feature. I'm going to close this issue, please use `PRESERVE: true` in your workflow to enable this feature. If you experience any problems please open up a new issue so they can be properly tracked/prioritized.

Thanks everyone!

**Closed by JamesIves** 2020-09-27 18:44 UTC
Labels: feature request, planned 🕘, testing, version 3

**Comment by oldgalileo** [comment] 2020-09-27 20:19
Awesome stuff. Testing out the 3.6.2 release on our internal sites and hopefully if all is well we'll be running this on production by the end of the week. Thanks!
